<script src="<?php echo $link_template ?>/js/jquery-3.2.1.min.js"></script>
<script src="<?php echo $link_template ?>/js/popper.js"></script>
<script src="<?php echo $link_template ?>/js/bootstrap.min.js"></script>
<script src="<?php echo $link_template ?>/js/stellar.js"></script>
<script src="<?php echo $link_template ?>/js/jquery.magnific-popup.min.js"></script>
<script src="<?php echo $link_template ?>/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="<?php echo $link_template ?>/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="<?php echo $link_template ?>/vendors/isotope/isotope-min.js"></script>
<script src="<?php echo $link_template ?>/vendors/owl-carousel/owl.carousel.min.js"></script>
<!-- <script src="<?php echo $link_template ?>/js/jquery.ajaxchimp.min.js"></script> -->
<script src="<?php echo $link_template ?>/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="<?php echo $link_template ?>/vendors/counter-up/jquery.counterup.min.js"></script>
<!-- <script src="<?php echo $link_template ?>/js/mail-script.js"></script> -->
<script src="<?php echo $link_template ?>/js/gmaps.min.js"></script>
<script src="<?php echo $link_template ?>/js/theme.js"></script>